POST http://localhost:8080/auth/create-admin HTTP/1.1

Content-Type: application/json

{
  "username": "AnAdmin",
  "password": "somepasswordlol"
}

###

GET http://localhost:8080/auth/admin-exists HTTP/1.1