POST http://localhost:8080/api/content-type HTTP/1.1
Content-Type: application/json

{
  "name": "post",
  "fields": [
    {
      "name": "title",
      "type": "text",
      "required": true
    },
    {
      "name": "body",
      "type": "text",
      "required": true
    },
    {
      "name": "image_ref",
      "type": "text",
      "required": true
    }
  ]
}

###

POST http://localhost:8080/api/content-type HTTP/1.1
Content-Type: application/json

{
  "name": "heading",
  "fields": [
    {
      "name": "page heading",
      "type": "text",
      "required": true
    },
    {
      "name": "paragraph heading 1",
      "type": "text",
      "required": true
    }
  ]
}